image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker build --target testrunner -t foundatio:test .
    - mkdir artifacts
    - docker run -v $(pwd)/artifacts:/app/artifacts foundatio:test
    - docker build --target publish -t foundatio:publish .
    - docker run --rm -it foundatio:publish
