name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build --target testrunner -t foundatio:test --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
      env:
        VERSION_SUFFIX: 1-pre
    - name: Test
      run: docker run -v $(pwd)/artifacts:/app/artifacts foundatio:test
    - name: Pack
      run: docker build --target pack -t foundatio:pack --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
      env:
        VERSION_SUFFIX: 1-pre
      
