name: Build
on: [push, pull_request]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install MinVer
      run: dotnet tool install --global minver-cli --version 2.0.0
    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
    - name: Build Version
      run: minver -t v
    - name: Build
      run: dotnet build --configuration Release --nologo
    - name: Run Tests
      run: dotnet test --configuration Release --nologo --results-directory artifacts --no-build --logger:trx
    - name: Package
      if: github.event_name != 'pull_request'
      run: dotnet pack --configuration Release --output artifacts --no-build
    - name: Push CI Packages
      if: github.event_name != 'pull_request'
      run: ./build/push.sh https://f.feedz.io/foundatio/foundatio/nuget ${{ secrets.FEEDZ_KEY }}
    - name: Push Release Packages
      if: startsWith(github.ref, 'refs/tags/v')
      run: ./build/push.sh https://api.nuget.org/v3/index.json ${{ secrets.NUGET_KEY }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: packages
        path: artifacts
