name: Build
on:
  workflow_call:
    inputs:
      solution:
        description: 'The solution to build'
        default: ''
        required: false
        type: string
      org:
        description: 'The organization to publish CI builds to'
        default: 'foundatiofx'
        required: false
        type: string
      compose-command:
        description: 'The docker compose command to run for tests'
        default: 'docker compose up -d && docker compose up ready || true'
        required: false
        type: string
    secrets:
      NUGET_KEY:
        required: false
      FEEDZ_KEY:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Build Reason
      run: |
        branch=${GITHUB_REF##*/}.
        if [[ "$branch" = "main." ]]; then
          branch=""
        elif [[ "$branch" = "master." ]]; then
          branch=""
        elif [[ "${GITHUB_REF}" = refs/tags* ]]; then
          branch=""
        elif [[ "${GITHUB_REF}" = refs/pull* ]]; then
          branch=""
        fi
        echo "GIT_BRANCH_SUFFIX=$branch" >> $GITHUB_ENV
        echo branch: $branch ref: $GITHUB_REF event: $GITHUB_EVENT_NAME actor: $GITHUB_ACTOR
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 6.0.0
        version=$(minver --tag-prefix v --default-pre-release-identifiers alpha.${GIT_BRANCH_SUFFIX}0)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "### Version: $version" >> $GITHUB_STEP_SUMMARY
    - name: Set Default Solution
      id: slnx
      run: |
        if [ -z "${{ inputs.solution }}" ]; then
          slnx=$(find . -maxdepth 1 -name "*.slnx" | head -n 2)
          count=$(echo "$slnx" | wc -l)
          if [ "$count" -eq 1 ]; then
            file=$slnx
          else
            file="${{ inputs.solution }}"
          fi
        else
          file="${{ inputs.solution }}"
        fi
        echo "file=$file" >> $GITHUB_OUTPUT
    - name: Build
      run: dotnet build ${{ steps.slnx.outputs.file }} --configuration Release
    - name: Start Services
      if: hashFiles('docker-compose.yml') != ''
      run: ${{ inputs.compose-command }}
    - name: Run Tests
      run: dotnet test ${{ steps.slnx.outputs.file }} --configuration Release --no-build --logger GitHubActions
    - name: Package
      if: github.event_name != 'pull_request'
      run: dotnet pack ${{ steps.slnx.outputs.file }} --configuration Release --no-build
    - name: Publish CI Packages
      if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
      run: |
        for package in $(find -name "*.nupkg" | grep "minver" -v); do

          # GitHub
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "${0##*/}": Pushing $package to GitHub...
            dotnet nuget push $package --source https://nuget.pkg.github.com/${{ inputs.org }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          fi

          # Feedz (remove once GitHub supports anonymous access)
          if [ -n "${{ secrets.FEEDZ_KEY }}" ]; then
            echo "${0##*/}": Pushing $package to Feedz...
            dotnet nuget push $package --source https://f.feedz.io/foundatio/foundatio/nuget --api-key ${{ secrets.FEEDZ_KEY }} --skip-duplicate
          fi

        done
    - name: Publish Release Packages
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        for package in $(find -name "*.nupkg" | grep "minver" -v); do
          echo "${0##*/}": Pushing $package...
          dotnet nuget push $package --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
        done
